# Generated by Django 3.1.1 on 2020-09-15 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_comment_replies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='replies',
            new_name='reply',
        ),
    ]
