# Generated by Django 3.0.2 on 2020-09-16 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_comment_parent'),
        ('main_app', '0002_sighting_species'),
    ]

    operations = [
    ]
