# Generated by Django 3.0.2 on 2020-09-16 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200915_0956'),
        ('main_app', '0010_remove_comment_parent'),
    ]

    operations = [
    ]
