# Generated by Django 3.1 on 2020-09-17 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_comment_parent'),
        ('main_app', '0003_auto_20200915_0956'),
    ]

    operations = [
    ]
