# Generated by Django 3.1 on 2020-09-17 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_merge_20200916_2134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sighting',
            options={},
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('sighting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.sighting')),
            ],
        ),
    ]
