# Generated by Django 3.1 on 2020-09-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20200920_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='location',
            field=models.CharField(default='Los Angeles, CA', max_length=100),
            preserve_default=False,
        ),
    ]
